///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: src/music/Demo.aks
/// Generation time: lun 10 jun 2024 20:30:07 CEST
///

/// Song 'Demo' metadata macros
#define Demo_address  0x6000
#define Demo_size     1121
#define Demo_end      0x6460

/// Song 'Demo' array declaration
extern void Demo[Demo_size];
