///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: src/music/ingame.sks
/// Generation time: jue 06 jun 2024 21:02:42 CEST
///

/// Song 'Demo' metadata macros
#define Demo_address  0x6000
#define Demo_size     1950
#define Demo_end      0x679d

/// Song 'Demo' array declaration
extern void Demo[Demo_size];
