///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: src/music/KellyOn.sks
/// Generation time: jue 06 jun 2024 21:00:38 CEST
///

/// Song 'Demo' metadata macros
#define Demo_address  0x6000
#define Demo_size     3545
#define Demo_end      0x6dd8

/// Song 'Demo' array declaration
extern void Demo[Demo_size];
