///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: src/music/Smoke.sks
/// Generation time: jue 06 jun 2024 20:59:24 CEST
///

/// Song 'Demo' metadata macros
#define Demo_address  0x6000
#define Demo_size     630
#define Demo_end      0x6275

/// Song 'Demo' array declaration
extern void Demo[Demo_size];
