void control_interrupciones();
void borra();
void teclado();
void fisica();
void iniciar_valores();
void mientras_juego();
void pintar_spites();
void suma_puntos();
void muere();
void comprobar_recojida();
void fisica_objetos();
void pintar_sprites();
void borra_objeto(u8 ,u8 ,u8 ,u8 );
void baja();
void sube();
void espera_pulsacion_tecla();