void control_interrupciones();
void borra();
void teclado();
void fisica();
void iniciar_valores();
void mientras_juego();
void pintar_spites();
void suma_puntos(u8);
void muere(u8 i);
void comprobar_recojida(u8 );
void fisica_objetos();
void pintar_sprites();
void borra_objeto(u8 ,u8 ,u8 ,u8 );
void baja();
void sube();
void espera_pulsacion_tecla();
void   inicia_objetos();
void menu_juego();
void a_jugar();
void pinta_marcador();
void espera_pulsar();
void fin_juego();
void pinta_puntos();

